/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts_xir4_12;

import java.text.SimpleDateFormat;

/**
 *
 * @author Enggar R S
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        denda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tpinjam = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tkembali = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        judul = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        bPrint = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("PERPUSTAKAAN COASTER ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 760, 90));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("NewsGoth Lt BT", 1, 14)); // NOI18N
        jLabel2.setText("Status");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));
        jPanel2.add(denda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 160, 30));

        jLabel3.setFont(new java.awt.Font("NewsGoth Lt BT", 1, 14)); // NOI18N
        jLabel3.setText("No Anggota");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel2.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 30));

        jLabel4.setFont(new java.awt.Font("NewsGoth Lt BT", 1, 14)); // NOI18N
        jLabel4.setText("Nama Peminjam");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel2.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 30));

        jLabel5.setFont(new java.awt.Font("NewsGoth Lt BT", 1, 14)); // NOI18N
        jLabel5.setText("Alamat Peminjam");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("NewsGoth Lt BT", 1, 14)); // NOI18N
        jLabel6.setText("Jenis Buku");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        jPanel2.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, 30));

        jLabel7.setFont(new java.awt.Font("NewsGoth Lt BT", 1, 14)); // NOI18N
        jLabel7.setText("Judul Buku");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
        jPanel2.add(tpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 180, 30));

        jLabel8.setFont(new java.awt.Font("NewsGoth Lt BT", 1, 14)); // NOI18N
        jLabel8.setText("Tanggal Pinjam");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 328, -1, 0));

        jLabel9.setFont(new java.awt.Font("NewsGoth Lt BT", 1, 14)); // NOI18N
        jLabel9.setText("Tanggal Pinjam");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));
        jPanel2.add(tkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 180, 30));

        jLabel10.setFont(new java.awt.Font("NewsGoth Lt BT", 1, 14)); // NOI18N
        jLabel10.setText("Tanggal Kembali");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));
        jPanel2.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 160, 30));

        jLabel11.setFont(new java.awt.Font("NewsGoth Lt BT", 1, 14)); // NOI18N
        jLabel11.setText("Denda");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        rb1.setText("Kembali");
        jPanel2.add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));

        rb2.setText("Belum Kembali");
        jPanel2.add(rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, -1, -1));

        rb3.setText("Pelajaran");
        jPanel2.add(rb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        rb4.setText("Pengetahuan Umum");
        jPanel2.add(rb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        rb5.setText("Komik/Novel");
        jPanel2.add(rb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 680));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NoAnggota", "NamaPeminjam", "AlamatPeminjam", "JenisBuku", "JudulBuku", "TanggalPinjam", "TanggalKembali", "Denda", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 870, 120));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 890, 490));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bPrint.setText("Print");
        jPanel4.add(bPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 80, 30));

        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        jPanel4.add(bSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 80, 30));

        bClear.setText("Clear");
        jPanel4.add(bClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 70, 30));

        bDelete.setText("Delete");
        jPanel4.add(bDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 90, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 600, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal1 = dateFormat.format(tpinjam.getDate());
        String tanggal2 = dateFormat.format(tkembali.getDate());
        
        String jenis ="";
        if (rb3.isSelected()) {
        } else {
            jenis ="Pelajaran";
        }
        if (rb4.isSelected()) {
        } else {
            jenis="Pengetahuan Umum";
        }
        if (rb5.isSelected()) {
            jenis= rb5.getText();
        } 
        String status = "";
        if (rb1.isSelected()) {
            } else {
                status = "Kembali";
        }
        if (rb2.isSelected()) {
           status = "Belum Kembali";
           
            if (no.getText().equals("") || nama.getText().equals("") || alamat.getText().equals("") ) {
                
            }
        }
    }//GEN-LAST:event_bSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bPrint;
    private javax.swing.JButton bSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField denda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField judul;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField no;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private com.toedter.calendar.JDateChooser tkembali;
    private com.toedter.calendar.JDateChooser tpinjam;
    // End of variables declaration//GEN-END:variables
}
